// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: File.proto

package com.message.proto;

public interface FileRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.message.proto.FileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes file = 1;</code>
   */
  com.google.protobuf.ByteString getFile();
}
