// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: File.proto

package com.message.proto;

public interface FileReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.message.proto.FileReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
