// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Query.proto

package com.message.proto;

public final class QueryProto {
  private QueryProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_message_proto_QueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_message_proto_QueryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_message_proto_QueryReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_message_proto_QueryReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Query.proto\022\021com.message.proto\"\035\n\014Quer" +
      "yRequest\022\r\n\005query\030\001 \001(\t\"\035\n\nQueryReply\022\017\n" +
      "\007message\030\001 \001(\t2X\n\007Greeter\022M\n\tSendQuery\022\037" +
      ".com.message.proto.QueryRequest\032\035.com.me" +
      "ssage.proto.QueryReply\"\000B\'\n\021com.message." +
      "protoB\nQueryProtoP\001\242\002\003HLWb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_message_proto_QueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_message_proto_QueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_message_proto_QueryRequest_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_com_message_proto_QueryReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_message_proto_QueryReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_message_proto_QueryReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
