// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Query.proto

package com.message.proto;

public interface QueryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.message.proto.QueryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string query = 1;</code>
   */
  java.lang.String getQuery();
  /**
   * <code>string query = 1;</code>
   */
  com.google.protobuf.ByteString
      getQueryBytes();
}
