// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Query.proto

package com.message.proto;

public interface QueryReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.message.proto.QueryReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
